---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-dev
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*
spec:
  releaseName: echo-dev
  chart:
    git: git@github.com:MaybeOron/echoFlux
    path: charts/echo
    ref: master
  values:
    app:
      image: oroncohen/echo
      tag: 1.0.1
    replicaCount: 1
    hpa:
      enabled: false
