---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~1.0
spec:
  releaseName: echo-dev
  chart:
    git: git@github.com:MaybeOron/echoFlux
    path: charts/podinfo
    ref: master
  values:
    app:
      image: oroncohen/echo
      tag: 1.0.0
    replicaCount: 1
    hpa:
      enabled: false
