---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-prod
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    repository.fluxcd.io/app: app.image # image value [ values.app.image ]
    tag.fluxcd.io/app: app.tag # tag value [ values.app.image ]
    filter.fluxcd.io/app: semver:~1.0 # what will get update -> the tag
spec:
  releaseName: echo-prod
  chart:
    git: git@github.com:MaybeOron/echoFlux
    path: charts/echo
    ref: master
  values:
    app:
      namespace: prod
      image: oroncohen/echo
      name: echo-prod
      tag: 1.0.8
    replicaCount: 1
