apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: echo-app
  namespace: default
spec:
  dnsNames:
    - {{ .Values.domain.url }}
  secretName: echo-secret-tls-sec
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer