apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name | default "app" }}-ip
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app.name | default "app" }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{ .Values.app.port | default 3000 }}
    - name: https
      protocol: TCP
      port: 443
      targetPort: {{ .Values.app.port | default 3000 }}