apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name | default "app" }}-configmap
data:
  PORT: "3000"
  LOGLEVEL: "info"
  PERSIST: "true"
  #MONGODBURL: "mongodb://mongo:mongo@mongo-echo-mongodb-0.mongo-echo-mongodb-headless:27017,mongo-echo-mongodb-1.mongo-echo-mongodb-headless:27017/echodb"
  DBNAME: "echodb"