apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-ingress
  namespace: {{ .Values.app.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
  labels:
    name: echo-ingress
spec:
  # tls:
  # - hosts:
  #   - {{ .Values.domain.url }}
  #   secretName: echo-secret-tls-sec-cqx7l
  #   #secretName: echo-secret-tls-sec
  #   #secretName: echo-secret-tls-q8ths
  rules:
  - host: {{ .Values.domain.url }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.app.name | default "app" }}-ip
            port: 
              number: 80
